# Read the documentation: https://fosrestbundle.readthedocs.io/en/3.x/
fos_rest:
    param_fetcher_listener: true
    view:
        view_response_listener: 'force'
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: 'json' }
            - { path: '^/api', priorities: ['json', 'html'], fallback_format: html, prefer_extension: true }
            - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: ~, prefer_extension: true }


    body_listener: true
