api_platform:
    resource: .
    type: api_platform
    prefix: /api
# config/routes/api.yaml
clients_get_all:
    path: '/clients'
    methods: [POST]
    controller: App\Controller\ClientController::getAllClients
